SELECT '2024-02-01';  ---DATE HERE IS IDENTIFIED AS STRING


SELECT
    '2024-02-02':: DATE,  --- STRING >>>>> DATE   DATA TYPE
    '123'::INT,    --- STRING >>>>> INTEGAR   DATA TYPE
    'TRUE'::BOOLEAN,  --- STRING >>> BOOLEAN  DATA TYPE
    '3.14'::NUMERIC;  --- STRING >>> NUMERIC DATA TYPE